default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  hostname:
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: travelblog_dev

test:
  <<: *default
  database: travelblog_test

production:
  <<: *default
  database: travelblog
